// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytbkygmkyedaqgoilwyc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Ymt5Z21reWVkYXFnb2lsd3ljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MDk0NjIsImV4cCI6MjA3MDQ4NTQ2Mn0.L1MvwiVdlhUccvL9ztyKL6uEm73icqzNvAd0cZz7i_o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});